services:
  redis:
    image: redis:7-alpine
    container_name: dev-redis
    command: >
      redis-server
        --appendonly no
        --save ""
        --notify-keyspace-events Ex
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 30
    restart: unless-stopped
